<?php

 session_start();

if(!(isset($_POST['email']) && isset($_POST['amt']))){

header("Location: /");
die();
}

else{

$_SESSION["IsPaid"] = 120;
$_SESSION["amt"]= $_POST["amt"];

}

?>


<html>
 <title>Select Payment Gateway</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Raleway:300,600" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'><link rel="stylesheet" href="./style.css">



<span style="color:white;font-weight:bold"><h1>Active Payment Methods :</h1></span>
<center><span style="color:white;font-weight:bold"><h3>This Page is highly secure and monitored by PSF</h3></span></center>


<br>
<?php

 $apiKey = "rzp_live_VgIPwTuLKzWYDc";

?>


<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<center>

<form action="Suc.php" method="POST">
<input type="hidden" value="<?php echo $amt*100;?>" name="hidden_amt">
<br><br><br>
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amt'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Secure Payment With Razorpay"
    data-name="Potti Sreeramulu Foudation"
    data-description="Donation Payment Gateway"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="blue"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">




</form>


<br><br>
<form method="POST" action="pgRedirect.php">


			
<input type="hidden" id="ORDER_ID" tabindex="1" maxlength="20" size="20"
						name="ORDER_ID" autocomplete="off"
						value="<?php echo  "ORDS" . rand(10000,99999999)?>">


<input type="hidden" id="CUST_ID" tabindex="2" maxlength="12" size="12" name="CUST_ID" autocomplete="off" value="payment_page_web_cust">
					


<input type="hidden" id="INDUSTRY_TYPE_ID" tabindex="4" maxlength="12" size="12" name="INDUSTRY_TYPE_ID" autocomplete="off" value="Retail"></td>
				

<input type="hidden" id="CHANNEL_ID" tabindex="4" maxlength="12"
						size="12" name="CHANNEL_ID" autocomplete="off" value="WEB">
					

<input title="TXN_AMOUNT" tabindex="10"
						type="hidden" type="text" name="TXN_AMOUNT"
						value="<?php echo $_POST['amt'];?>">
	
<input type="hidden" id="phone" tabindex="4" maxlength="12" size="12" name="phone" autocomplete="off" value="<?php echo $_POST['mobile'];?>"></td>

<input type="hidden" id="phone" tabindex="4" maxlength="12" size="12" name="email" autocomplete="off" value="<?php echo $_POST['email'];?>"></td>				

<input value="Secure Payment With PAYTM" type="submit"	onclick="" id="sub"><BR>(PAYTM TAKES UPTO 2 HOURS FOR INVOICE GENARATION)
				
</form>
<FOOTER>
<P>Made By : <a href="https://thedj.tech/" target="black"> DJ </P>
</FOOTER>

</center>
</html>

